# To troubleshoot and get more log info enable ldap debug logging in grafana.ini
# [log]
# filters = ldap:debug

[[servers]]
### THIS MAY NEED ADJUSTEMENT IN YOUR CASE ####
# Ldap server host (specify multiple hosts space separated)
host = "ldapserver.domain.com"
# Default port is 389 or 636 if use_ssl = true
port = 636
# Set to true if LDAP server should use an encrypted TLS connection (either with STARTTLS or LDAPS)
use_ssl = true
# If set to true, use LDAP with STARTTLS instead of LDAPS
start_tls = false
# set to true if you want to skip ssl cert validation
ssl_skip_verify = true
# set to the path to your root CA certificate or leave unset to use system defaults
# root_ca_cert = "/path/to/certificate.crt"
# Authentication against LDAP servers requiring client certificates
# client_cert = "/path/to/client.crt"
# client_key = "/path/to/client.key"

# Search user bind dn
#bind_dn = "cn=admin,DC=comafana,dc=org"
bind_dn = "CN=ldapusername,OU=Users,DC=domain,DC=com"
# Search user bind password
# If the password contains # or ; you have to wrap it with triple quotes. Ex """#password;"""
#bind_password = 'grafana'
bind_password = 'thepassword'

# User search filter, for example "(cn=%s)" or "(sAMAccountName=%s)" or "(uid=%s)"
#search_filter = "(cn=%s)"
### THIS MAY NEED ADJUSTEMENT IN YOUR CASE ####
search_filter = "(sAMAccountName=%s)"

# An array of base dns to search through.
### THIS MAY NEED ADJUSTEMENT IN YOUR CASE ####
#search_base_dns = ["DC=comafana,dc=org"]
search_base_dns = ["OU=Users,DC=domain,DC=com"]

## For Posix or LDAP setups that does not support member_of attribute you can define the below settings
## Please check grafana LDAP docs for examples
# group_search_filter = "(&(objectClass=posixGroup)(memberUid=%s))"
# group_search_base_dns = ["ou=groups,DC=comafana,dc=org"]
### THIS MAY NEED ADJUSTEMENT IN YOUR CASE ####
group_search_base_dns = ["DC=domain,DC=com"]
# group_search_filter_user_attribute = "uid"

# Specify names of the ldap attributes your ldap uses
[servers.attributes]
name = "givenName"
surname = "sn"
#username = "cn"
username = "sAMAccountName"
member_of = "memberOf"
email =  "email"

# Map ldap groups to grafana org roles
### THIS MAY NEED ADJUSTEMENT IN YOUR CASE ####
[[servers.group_mappings]]
#group_dn = "cn=admins,ou=groups,DC=comafana,dc=org"
group_dn = "CN=NwmonAdmins,OU=Groups,OU=Users,DC=domain,DC=com"
org_role = "Admin"
# To make user an instance admin  (Grafana Admin) uncomment line below
# grafana_admin = true
# The Grafana organization database id, optional, if left out the default org (id 1) will be used
# org_id = 1

[[servers.group_mappings]]
### THIS MAY NEED ADJUSTEMENT IN YOUR CASE ####
#group_dn = "cn=users,ou=groups,DC=comafana,dc=org"
group_dn = "CN=NwmonEditors,OU=Groups,OU=Users,DC=domain,DC=com"
org_role = "Editor"

[[servers.group_mappings]]
### THIS MAY NEED ADJUSTEMENT IN YOUR CASE ####
# If you want to match all (or no ldap groups) then you can use wildcard
#group_dn = "*"
group_dn = "CN=Grafana-viewers,OU=Groups,OU=Users,DC=domain,DC=com"
org_role = "Viewer"
